---
- hosts: mongodb
  tasks:
    # create /data/mongodb
    - name: create a folder data 
      file: 
        path: /data/mongodb 
        state: directory
      become: true
  
    #create parttion 
    - name: create parttion 
      parted:
        device: /dev/sdb 
        number: 1
        state: present
      become: true
    
    #format parttion
    - name: format parttion
      command: mkfs -t ext4 /dev/sdb1
      become: true

    # mount file system
    - name: mount extra disk
      vars:
        mount_path: /data/mongodb
        mount_src: /dev/sdb1
      mount:
        path: "{{mount_path}}"
        src: "{{mount_src}}"
        fstype: ext4
        state: mounted
      become: true