---
- hosts: mongodb
  tasks:
   
    - name: stop mongodb service  
      service: 
        name: mongod
        state: stopped
      become: true

    - name: delete default config
      file:
        path: /etc/mongod.conf
        state: absent
      become: true
      
    # enable replicaset file config
    - name: copy file to remote host
      copy: 
        src: ../files/replicaset.conf
        dest: /etc/mongod.conf

    - name: restart mongodb service
      service:
        name: mongod
        state: restarted
      become: true