---
- hosts: mongodb
  vars_files:
    - ../vars/main.yml
  tasks:
    # create /data/mongodb
    - name: create a folder data 
      ansible.builtin.file: 
        
        path: "{{ mounted_path }}"
        state: directory
      become: true
  
    #create parttion 
    - name: create parttion 
      parted:
        device: "{{ mounted_disk }}"
        number: 1
        state: present
      register: _mounted_disk_number
      become: true
    
    #format parttion
    - name: format parttion
      command: mkfs -t ext4 /dev/sdb1
      become: true

    # mount file system
    - name: mount extra disk
      mount:
        path: "{{ mounted_path }}"
        src: /dev/sdb1
        fstype: "{{ file_system_type }}"
        state: mounted
      become: true
 
    #
    - name: add mongodb repo 
      ansible.builtin.apt_key:
        url: "{{ mongo_repo }}"
        state: present
        validate_certs: false
      become: true 
      retries: 5
    #
    - name: create list file version
      command: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      become: true
      retries: 5
      #notify: 
      #  - apt update
    - name: apt update
      ansible.builtin.apt:
        upgrade: yes
        update-cache: yes 
        allow_unauthenticated: true
      become: true
      retries: 5

    # install mongodb-org
    - name: install mongodb-org
      ansible.builtin.apt: 
        name: mongodb-org
        state: present
      become: true
    
    #move default mongodb folder to disk mounted  
    - name: mv mongodb default folder to /data/mongodb
      ansible.builtin.copy:
        remote_src: true
        src: "{{ mongo_default_folder }}"
        dest: "{{ mounted_path }}"
      #notify:
      #  - stop mongodb
      become: true

    #stop mongdodb service
    - name: stop mongodb        
      ansible.builtin.service:
        name: mongod
        state: stopped
      become: true

    #change owner new folder
    - name: change owner to mongodb
      ansible.builtin.file:
        path: /data/mongodb
        owner: "{{ mongo_user }}"
        group: "{{ mongo_group }}"

    # delete default folder
    - name: delete mongodb default folder
      ansible.builtin.file:
        path: "{{ mongo_default_folder }}"
        state: absent 
      become: true

    # create a symlink
    - name: create a symlink 
      ansible.builtin.file:
        src: "{{ mounted_path }}"
        dest: "{{ mongo_default_folder }}"
        owner: "{{ mongo_user }}"
        group: "{{ mongo_group }}"
        state: link
      #notify:
      #  - restart mongodb

    # handlers file for mongodb-all
    - name: restart mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted
      become: true