---
- hosts: mongodb
  tasks:
    # create /data/mongodb
    - name: create a folder data 
      file: 
        path: /data/mongodb 
        state: directory
      become: true
  
    #create parttion 
    - name: create parttion 
      parted:
        device: /dev/sdb 
        number: 1
        state: present
      become: true
    
    #format parttion
    - name: format parttion
      command: mkfs -t ext4 /dev/sdb1
      become: true

    # mount file system
    - name: mount extra disk
      vars:
        mount_path: /data/mongodb
        mount_src: /dev/sdb1
      mount:
        path: "{{mount_path}}"
        src: "{{mount_src}}"
        fstype: ext4
        state: mounted
      become: true

    - name: add mongodb repo 
      apt_key:
        url: "https://www.mongodb.org/static/pgp/server-6.0.asc"
        state: present
      become: true 

    - name: create list file version
      command: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      become: true
    
    - name: apt update
      apt:
        update-cache: yes 
      become: true
    #check repository
    #- name: check mongodb in repository yet
    #   apt_repository:
    #- name: Ensure MongoDB apt repository exists
    #  apt_repository:
    #    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/6.0 multiverse"
    #    state: present
        #filename: "mongodb-{{ mongodb_version }}"

    # install mongodb-org
    - name: install mongodb-org
      apt: 
        name: mongodb-org
        state: latest 
      become: true

    #stop mongdodb service
    - name: stop mongodb
      service:
        name: mongod
        state: stopped
      become: true
    
    #move default mongodb folder to disk mounted  
    - name: mv mongodb default folder to /data/mongodb
      copy:
        src: /var/lib/mongodb
        dest: /data/mongodb 
    #change owner new folder
    - name: change owner to mongodb
      file:
        path: /data/mongodb
        owner: "mongodb"
        group: "mongodb"
    # delete default folder
    - name: delete mongodb default folder
      file:
        path: /var/lib/mongodb 
        state: absent 

    # create a symlink
    - name: create a symlink 
      file:
        src: /data/mongodb
        dest: /var/lib/mongodb
        owner: mongodb
        group: mongodb
        state: link

    # change owner to new parttion
    #- name: change owner db to mongodb user
    - name: start mongodb
      service:
        name: mongod
        state: restarted
      become: true
